
# erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
# Slash 4x4 Platinum 1/10 scale traxxas RC truck:
# overall fd ratio: 11.82
# tire diam - stock, unladen: 4.3 in / 0.109 m
# distance / rev_wheel: 0.342 m / rev
# speed_to_erpm_gain: 1/0.342* rev / m * m / s * 11.82 rev_electrical / rev_mech * 60 rpm / rps
speed_to_erpm_gain: 2073
speed_to_erpm_offset: 0.0

tachometer_ticks_to_meters_gain: 0.00225
# servo smoother - limits rotation speed and smooths anything above limit
max_servo_speed: 2.2 # radians/second
servo_smoother_rate: 75.0 # messages/sec

# servo smoother - limits acceleration and smooths anything above limit
max_acceleration: 4.0 # meters/second^2
throttle_smoother_rate: 75.0 # messages/sec

# servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
# Measurement - Traxxis Slash - Stock steering setup
# servo_: 0.933, turning circle: 55 inches / 1.397 m @ center of car
# bicycle model:
# a = steering wheel angle
# W = wheelbase
# R = radius of turn
# a@0.933 = asin( w / R )
# a@0.933 = asin( 0.324 / (1/2*1.397) )
# a@0.933 = -0.482 rad
# gain = (-0.482 rad - offset) / 0.933
# ^above does not work well, believe actual steering not very akermann like near limits
# a@0.1976
# measurement: @0.2845 duty cycle, turning circle = 2.44 m, which corresponds to 0.2688 rad (asin(.324 / (1/2*2.44) )
steering_angle_to_servo_gain: -0.7645
steering_angle_to_servo_offset: 0.490

# publish odom to base link tf
vesc_to_odom/publish_tf: false

# traxis slash wheelbase is 32.4 cm
wheelbase: .324

vesc_driver:
  port: /dev/ttyACM0
  duty_cycle_min: 0.0
  duty_cycle_max: 0.0
  current_min: 0.0
  current_max: 20.0
  brake_min: -20000.0
  brake_max: 200000.0
  speed_min: -3250
  speed_max: 15250   # 15000: ~ 25 kph / 7 mps
  position_min: 0.0
  position_max: 0.0
  servo_min: 0.075
  servo_max: 0.933
